### ISSUE TITLE
NTQDFPath

### ISSUE THREAD

**Issue by HamedOv** [jszhtian/Fragment#1]
Hi,

Would you please provide a compiled ready to use version of the dll.

Thank you so much,
Hamed

**Comment by jszhtian** [comment]
[loder.zip](https://github.com/jszhtian/Fragment/files/2299958/loder.zip)

You need use Loader.exe or other tools to inject the NTQDFPatch.dll to target process.
For Themida protected application, the application maybe fail to startup, and report some errors.
