### ISSUE TITLE
yu-ris engine

### ISSUE THREAD

**Issue by imKota** [jszhtian/Fragment#2]

**Comment by jszhtian** [comment]
Normal Yu-Ris engine games will load files from Loacl file system first instead load from ypf file, you only need to get texts from ybn files.
use some tools like extybn or handle it by yourself(https://github.com/regomne/chinesize/blob/master/yuris/extYbn/extYbn.go)
But some games use modification version, you maybe find something like this picture
![image](https://user-images.githubusercontent.com/23244094/71977229-8e866e00-3218-11ea-9fd6-ee751e42b293.png)
This part will decide the load localtion priority. Change it or rebuild ypf package.
I don't do any job in musiaca engine. so you need ask other programmers.

**Comment by imKota** [comment]
@jszhtian hmm
Can you show an example?
On trial ver [this](https://drive.google.com/open?id=1C9eal8YXNdmhgJhNx-O6NgqXNNBnmrKu) game?

**Comment by imKota** [comment]
@jszhtian i found 
![image](https://user-images.githubusercontent.com/24241471/71993878-e210b000-3248-11ea-8304-b10355513bc3.png)

What should I do next?

**Comment by jszhtian** [comment]
Open Ollydbg and check the file load routing, change 0123 sequence to force application load local file first.
Here is a example.([Whirlpool] pieces)
[pieces.zip](https://github.com/jszhtian/Fragment/files/4036196/pieces.zip)
Because of stupid Character Range check function, This game can only display Shift-JIS or ANSI character. If you want to display other character, you need change MBCS range check or build a Font File like console game.

**Comment by imKota** [comment]
@jszhtian The fact that the game reads scripts from a folder, I understood. But I can’t understand how to unpack the scripts themselves.

[bn.ypf](https://github.com/jszhtian/Fragment/files/4036223/bn.zip)

I can unpack **bn.ypf** but the scripts themselves ***.ybn** can not.

**Comment by jszhtian** [comment]
ybn file is encrypted. It needs decrypt first. Create Breakpoint on Createfile, when application load ybn file, deactive breakpoint, create breakpoint on readfile. When file load to buffer, create a memory breakpoint on buffer memory. Pay attention! you need skip YTSB file head, the size of head at least 0x20.
When memory breakpoint is triggered. Check the operation. Normally it is a XOR operation, Find the XOR operation operand, it should be a 4 bytes array.
If you find the correct array. you can use these tools to extract text from ybn files
https://github.com/regomne/chinesize/tree/master/yuris
For newer modifyed Yu-Ris system, the scenario files maybe some text files, and nothing in YBN files.
If you want to know more about YTSB file structure,
https://github.com/regomne/chinesize/blob/master/yuris/extYbn/
It will show you the structure of YTSB files.

**Comment by imKota** [comment]
@jszhtian I unpacked through garbro. 

[decrypted_ypf.zip](https://github.com/jszhtian/Fragment/files/4036540/decrypted_ypf.zip)

![image](https://user-images.githubusercontent.com/24241471/72001987-a3362680-3257-11ea-9f2f-be0a09cd6de7.png)
![image](https://user-images.githubusercontent.com/24241471/72002051-c365e580-3257-11ea-84c3-d5202a11f127.png)

And I found a key **0x61a3d035** for scripts.
What's next?

**Comment by jszhtian** [comment]
https://github.com/regomne/chinesize/blob/master/yuris/extYbn/extYbn.go
use his tools. It can extract text from ybn and rebuild it.
This tools is written by go language. I have compiled it before.
[extYbn.zip](https://github.com/jszhtian/Fragment/files/4036587/extYbn.zip)

**Comment by imKota** [comment]
> It can extract text from ybn and rebuild it.

Hmm.. errors

![image](https://user-images.githubusercontent.com/24241471/72003513-9b2bb600-325a-11ea-80c8-c4c2ee0f6cb4.png)
![image](https://user-images.githubusercontent.com/24241471/72003649-e2b24200-325a-11ea-91ef-aeeef631d712.png)

**Comment by imKota** [comment]
and on macOS

![image](https://user-images.githubusercontent.com/24241471/72004299-2a859900-325c-11ea-91aa-77e95bcf665c.png)

**Comment by jszhtian** [comment]
![image](https://user-images.githubusercontent.com/23244094/72005868-d45e2900-324e-11ea-9f7b-a001e0a7d164.png)
check the ybn key. **If the Text is stored in YBN file.** you can use Hex Editor find the text directly.
If you can see the Text in HexEditor, the ExtYbn should work.
If you decrypt ybn before use extybn, you should set key to 0.

**Comment by imKota** [comment]
@jszhtian Sorry.. i think I'm stupid...

Can you show an example on [euphoria trial ver](https://drive.google.com/open?id=1C9eal8YXNdmhgJhNx-O6NgqXNNBnmrKu)? 

![image](https://user-images.githubusercontent.com/24241471/72008594-388be780-3265-11ea-92c6-e787c7c68469.png)

Key:0xff
ScriptKey: 0x30731b78

**Comment by jszhtian** [comment]
The reason why you can not get correct ybn file is that you choose euphoria japanese edition protect scheme. It is incorrect for english trial version. If you use ollydbg directly dump file yst00113.ybn. you will see the difference.
Actually, if you unpack bn.ypf and put it to the directory, then modify the EXE file to force load file from ysbin directory. The game will crash. That means your files are incorrect. You should write a new protect scheme in GarBro to handle it.
In zip file, I provide a example, and you can see, if you use Incorrect_yst00113.ybn file, the application will directly crash, but yst00113.ybn can work as we expected.
You need analysis YPF structure and get correct YBN files first.
**Don't always rely on exist tools, they can't guarantee they can handle all situation.**
[euphoria trial.zip](https://github.com/jszhtian/Fragment/files/4037108/euphoria.trial.zip)
Now it's time to do some disassembly work.

**Comment by imKota** [comment]
> But some games use modification version, you maybe find something like this picture
> ![image](https://user-images.githubusercontent.com/23244094/71977229-8e866e00-3218-11ea-9fd6-ee751e42b293.png)
> This part will decide the load localtion priority. Change it or rebuild ypf package.

@jszhtian It's strange..
![11](https://user-images.githubusercontent.com/24241471/72266177-e402b680-362e-11ea-899b-b8f1eca5e85d.png)

**Comment by jszhtian** [comment]
In this game, you need change more than one times.
This priority looks like a force inline function. That means this part is exist in multiple positions.
Use IDA pro or other tools. You can see the different between this exe file and the original one.
[nekonin.zip](https://github.com/jszhtian/Fragment/files/4054227/nekonin.zip)

**Comment by imKota** [comment]
> You can see the different between this exe file and the original one.
> [nekonin.zip](https://github.com/jszhtian/Fragment/files/4054227/nekonin.zip)

app crash :D

**Comment by jszhtian** [comment]
Which version are you use?
This is the hash of exe file.
nekonin.exe SHA1
cd8d6895da33a4247f046689be036ce0c7ce7de4
nekonin_mod.exe
aeb07b110021eaa00deb96a87ce3b7e2e320982c

**Comment by imKota** [comment]
> Which version are you use?

english 
[nekonin.exe.zip](https://github.com/jszhtian/Fragment/files/4054266/nekonin.exe.zip)

Name: nekonin.exe
Size: 2116608 bytes (2067 KiB)
SHA1: 641BA88BB8CA8795705FA6423C2F024E60574B60

**Comment by imKota** [comment]
@jszhtian [this](https://drive.google.com/file/d/101vi0mwxoRgdf7P3EK7Fdr3Br5HeVn-0/view)

**Comment by jszhtian** [comment]
In my computer, your application is also crash.
I use a Traditional Chinese version for test, it include English version.
It maybe use the same sourcecode, but the protection scheme is different.
[nekonin.zip](https://github.com/jszhtian/Fragment/files/4054304/nekonin.zip)
I will upload the original one and the modification one.
Whirlpool games always use the modification version YU-RIS engine.

**Comment by imKota** [comment]
> I use a Traditional Chinese version for test, it include English version.
> It maybe use the same sourcecode, but the protection scheme is different.

Yes that's right. The problem is in the versions of the game..
Do you have a discord, or any realtime messenger ?

**Comment by jszhtian** [comment]
Unfortunately, I can not modify your version in short time because of examination.
Give you some suggestions, use API Monitor to see the different between the modification.
http://www.rohitab.com/downloads
Just monitor CreateFileA and GetFileAttributesA. These APIs will be recorded when application wants to load file directly.

**Comment by imKota** [comment]
@jszhtian if you have discord, please add me Kota#1914

**Comment by imKota** [comment]
@jszhtian Please write to me in the mail. aleksey-nyaka@yandex.ru

**Comment by imKota** [comment]
> If you want to display other character, you need change MBCS range check

And how do I do this?

**Comment by jszhtian** [comment]
For Whirlpool games, I suggest you to use SJIS Map method.
That means, map characters into shift-jis range. When Application uses TextOutA to draw character, hook it and replace the character. Because this version Yu-Ris engine not only includes normal character range check, but also includes something like “cmp ebx,0x9F”, and these asm code is not only for character range check. It maybe a part of parse of script in my opinion. That's why I don't suggest you to change the range check.
For normally Yu-RIS game, You can find a array near the TextOutA call. Which will check the higher MBCS byte, if the byte is in the Shift-JIS range, TextOutA parameter will be set to 2 bytes otherwise, will be set to 1.

**Comment by imKota** [comment]
> For Whirlpool games, I suggest you to use SJIS Map method.
> That means, map characters into shift-jis range. When Application uses TextOutA to draw character, hook it and replace the character. Because this version Yu-Ris engine not only includes normal character range check, but also includes something like “cmp ebx,0x9F”, and these asm code is not only for character range check. It maybe a part of parse of script in my opinion. That's why I don't suggest you to change the range check.
> For normally Yu-RIS game, You can find a array near the TextOutA call. Which will check the higher MBCS byte, if the byte is in the Shift-JIS range, TextOutA parameter will be set to 2 bytes otherwise, will be set to 1.

If I pay you, will you help solve the problem with Russian characters?
Since I have translated all the parts of "neko-nin", and I can’t release, because Russian characters are not displayed.

**Comment by imKota** [comment]
@jszhtian for example.

This is the beginning of the first 01.txt. From the first part of "neko-nin".

```
\LE("Мир, в котором мы живем, был создан Богами")
\LC("我們所生存的這個世界，是過去由神明所創造的??")   //The world we live in was created by gods.

\LE("Земли, сотворенные из крови и плоти божественных Матери и Отца.．")
\LC("這片大地等同於如父如母的神明的血肉。")   //The earth was both our mother and father. It was made of the flesh and blood of the gods.

\LE("Пришедшие из Такамагахары, Бог Отец и Мать сначала создали мир, а затем породили множество жизней.")
\LC("離開高天原的父神、母神一開始先創造了大地，接著一個個地?下許許多多的生命。")   //He and She came from Takamagahara to create the world, giving birth to countless lives in the process.

\LE("The mountains， the forests， the earth， and rivers．．． Men and beasts， as well．")
\LC("不論是山林、大地、河川……還有人類與野獸都是。")   //The mountains, the forests, the earth, and rivers…Men and beasts, as well.

\LE("All of creation were gifts of the divine．")
\LC("森羅萬象、所有的生命與生物，全部都是由神明所創造的。")   //All of creation were gifts of the divine.

```

![image](https://user-images.githubusercontent.com/24241471/72280415-53859f80-3649-11ea-8af0-b0fb8df645c7.png)

**Comment by jszhtian** [comment]
This is illegal in some countries because of copyright.
I can provide some examples for this.
https://github.com/jszhtian/Fragment/tree/master/ToHeart2_ScriptEngine
This is the patch of Kizuato, which is a very old leaf games. It uses a pre-rendered Font Files. So that I need map some GBK characters into Shift-JIS Kanji range.
It includes 2 parts. The injection and mapbuilder.
Injection will load translation text and check map array to get Shift-JIS index, combine with rebuild Font files, this game can display GBK characters.
Mapbuilder will collect all character which used in translation and create a map between GBK and ShiftJIS.

**Comment by imKota** [comment]
I definitely can’t figure it out myself.. So these translations are not destined to be released.

**Comment by imKota** [comment]
@jszhtian maybe you can help me out of interest? 😀

**Comment by imKota** [comment]
@jszhtian Tools not working :(
Can you help me?

**Comment by Jinkeel6667** [comment]
Interesting topic happened to me the same with the game Eroge! Sex and game
I managed to unzip the files
From bn.ypf I got 314 files in .ybn format, it is supposed that the sripts should be there to modify the game dialogs but it seems that they were encrypted and I could not access the scripts
How do you manage to extract the scripts with the dialogs of the .ybn files

**Comment by jszhtian** [comment]
> Interesting topic happened to me the same with the game Eroge! Sex and game
> I managed to unzip the files
> From bn.ypf I got 314 files in .ybn format, it is supposed that the sripts should be there to modify the game dialogs but it seems that they were encrypted and I could not access the scripts
> How do you manage to extract the scripts with the dialogs of the .ybn files

You should analysis the executable files first.
Normally, Yu-RIS engine use 4 bytes XOR operation to encrypt script files.
For some newer or modified Yu-RIS engine games. They maybe use plaintext to storage. In this situation, ybn files will not contain any script data.
If you don't want to analysis executable files. You can also try this unpacker. But I can not garentee it always works.
https://github.com/mwzzhang/python-YU-RIS-package-file-unpacker

**Comment by Jinkeel6667** [comment]
Well it doesn't work. I will have to analyze the executable files, could you explain to me how to do that job, which program I need, is my first time with .ybn files

![15851895322425626895202931772950](https://user-images.githubusercontent.com/62674538/77603942-4ace0700-6edf-11ea-969f-c80d17586a0c.jpg)

**Comment by jszhtian** [comment]
You can find some string like this "ysbin\\yst%05d.ybn".
Use IDA pro or ollydbg to find it. Then find which method use this const string.
It looks like this.
![image](https://user-images.githubusercontent.com/23244094/77642496-0c2b6180-6f5e-11ea-8ba1-3f6651d19409.png)
Here we can find a XOR loop. Normally, this is the decryption algorithm.
You can also set a memory breakpoint or hardware breakpoint, when engine load ybn file directly. But you need change load priority to ensure engine load ybn directly before load from ypf package.
Otherwise, you need find YSZLB.DLL's export Zlib Uncompress operation, and follow it to find the uncompressed data buffer.

**Comment by 7nc4** [comment]
I tried to extract script files from euphoria, but couldn't. I have tried various programs, but they do not help, and errors occur when I try to run Python scripts. 
Using IDA I found something similar to "ysbin\yst%05d.ybn", but what to do with it? Can you help to extract the scripts from euphoria?
[My ybn files with original exe and ypf file](https://github.com/jszhtian/Fragment/files/4441129/This.zip)
![Безымянный](https://user-images.githubusercontent.com/63266065/78611526-a05fc780-7880-11ea-9a6f-fbe5f854c2e9.jpg)

**Comment by mwzzhang** [comment]
> > Interesting topic happened to me the same with the game Eroge! Sex and game
> > I managed to unzip the files
> > From bn.ypf I got 314 files in .ybn format, it is supposed that the sripts should be there to modify the game dialogs but it seems that they were encrypted and I could not access the scripts
> > How do you manage to extract the scripts with the dialogs of the .ybn files
> 
> You should analysis the executable files first.
> Normally, Yu-RIS engine use 4 bytes XOR operation to encrypt script files.
> For some newer or modified Yu-RIS engine games. They maybe use plaintext to storage. In this situation, ybn files will not contain any script data.
> If you don't want to analysis executable files. You can also try this unpacker. But I can not garentee it always works.
> https://github.com/mwzzhang/python-YU-RIS-package-file-unpacker

It seems that I've stumbled onto this discussion by complete freak chance, but I guess this explains why people were forking that repo.

Yes, I wrote that unpacker as an exercise to reverse engineer VN engine file format following some tutorial articles online. It was a mostly blackbox (with the exception of the obfuscated names part) effort, and I was mostly interested in CGs and Voices/Musics because I could immediately see the results. While I suspected that ybn files had something to do with scripts, I didn't really have the time to look into it, not to mention that it was hard to see whether the results were correct or not.

If it's any help, the most important file in that unpacker is the ksy file. It is a Kaitai Struct format description language (read: YAML) file, and it describes the binary format of ypf file, and only ypf file, to the point where I could unpack all the CGs and sound files (and the ybn archive iirc). But I suspect there is nothing in there that you don't already know.

Ping me if you need any help regarding that unpacker.

**Comment by eliasstein** [comment]
Hi @jszhtian can you help me to modify the exe of eroge for read the ybn files? i tried but i can modify the priority :/

**Comment by Cosetto** [comment]
> Open Ollydbg and check the file load routing, change 0123 sequence to force application load local file first. Here is a example.([Whirlpool] pieces) [pieces.zip](https://github.com/jszhtian/Fragment/files/4036196/pieces.zip) Because of stupid Character Range check function, This game can only display Shift-JIS or ANSI character. If you want to display other character, you need change MBCS range check or build a Font File like console game.

Can you tell how to change MBCS range with Olldby? I want the game to read the script in utf8

**Comment by jszhtian** [comment]
> > Open Ollydbg and check the file load routing, change 0123 sequence to force application load local file first. Here is a example.([Whirlpool] pieces) [pieces.zip](https://github.com/jszhtian/Fragment/files/4036196/pieces.zip) Because of stupid Character Range check function, This game can only display Shift-JIS or ANSI character. If you want to display other character, you need change MBCS range check or build a Font File like console game.
> 
> Can you tell how to change MBCS range with Olldby? I want the game to read the script in utf8

Normal MBCS check is something like [cmp al,0x9F]. But the modify version Yu-Ris has their own MBCS check because it uses plaintext scenario instead of normal ybn file. Which means you need modify the parser which is written by the 3rd party. For my side, write a new Font file is much easy compared to modify custom MBCS check.

**Comment by Cosetto** [comment]
> > > Open Ollydbg and check the file load routing, change 0123 sequence to force application load local file first. Here is a example.([Whirlpool] pieces) [pieces.zip](https://github.com/jszhtian/Fragment/files/4036196/pieces.zip) Because of stupid Character Range check function, This game can only display Shift-JIS or ANSI character. If you want to display other character, you need change MBCS range check or build a Font File like console game.
> > 
> > 
> > Can you tell how to change MBCS range with Olldby? I want the game to read the script in utf8
> 
> Normal MBCS check is something like [cmp al,0x9F]. But the modify version Yu-Ris has their own MBCS check because it uses plaintext scenario instead of normal ybn file. Which means you need modify the parser which is written by the 3rd party. For my side, write a new Font file is much easy compared to modify custom MBCS check.

Tks for the tip. 
Btw if anyone looking for repacking .ypf ver 500 try this :https://github.com/davidescrima9/YPF_Manager_Tool
It can unpack/repack .ypf and print info of yu-ris version

**Comment by Sisulizer** [comment]
I still don't know how to guess the key for extybn but I found this https://web.archive.org/web/20140208002246/http://tlwiki.org/images/0/02/OzmafiaScriptThing.7z. Seems like it can auto guess the key and extract the text but I'm not sure if this is the full text since the tool is made for old Yu-ris. Btw I'm trying with golden hour (ver 500)
![image](https://user-images.githubusercontent.com/91543117/140052386-6d10b96b-7b78-4abb-8324-66d52f2afdd4.png)

**Comment by Sisulizer** [comment]
Oh wait I had to change encode of the script before extract and it worked nicely
![image](https://user-images.githubusercontent.com/91543117/140053268-fcea858e-108c-4120-ab25-0f3078eecfff.png)

**Comment by Cosetto** [comment]
> > > Open Ollydbg and check the file load routing, change 0123 sequence to force application load local file first. Here is a example.([Whirlpool] pieces) [pieces.zip](https://github.com/jszhtian/Fragment/files/4036196/pieces.zip) Because of stupid Character Range check function, This game can only display Shift-JIS or ANSI character. If you want to display other character, you need change MBCS range check or build a Font File like console game.
> > 
> > 
> > Can you tell how to change MBCS range with Olldby? I want the game to read the script in utf8
> 
> Normal MBCS check is something like [cmp al,0x9F]. But the modify version Yu-Ris has their own MBCS check because it uses plaintext scenario instead of normal ybn file. Which means you need modify the parser which is written by the 3rd party. For my side, write a new Font file is much easy compared to modify custom MBCS check.

Do you know how to wrap Yu-ris? I don't feel like using space for every word-wrap.
![image](https://user-images.githubusercontent.com/81801486/140083731-332afb34-e5e9-4374-b2bf-a0c220ef5c0d.png)

**Comment by imKota** [comment]
> > > > Open Ollydbg and check the file load routing, change 0123 sequence to force application load local file first. Here is a example.([Whirlpool] pieces) [pieces.zip](https://github.com/jszhtian/Fragment/files/4036196/pieces.zip) Because of stupid Character Range check function, This game can only display Shift-JIS or ANSI character. If you want to display other character, you need change MBCS range check or build a Font File like console game.
> > > 
> > > 
> > > Can you tell how to change MBCS range with Olldby? I want the game to read the script in utf8
> > 
> > 
> > Normal MBCS check is something like [cmp al,0x9F]. But the modify version Yu-Ris has their own MBCS check because it uses plaintext scenario instead of normal ybn file. Which means you need modify the parser which is written by the 3rd party. For my side, write a new Font file is much easy compared to modify custom MBCS check.
> 
> Do you know how to wrap Yu-ris? I don't feel like using space for every word-wrap. ![image](https://user-images.githubusercontent.com/81801486/140083731-332afb34-e5e9-4374-b2bf-a0c220ef5c0d.png)

try use `\n`

**Comment by Cosetto** [comment]
> > > > > Open Ollydbg and check the file load routing, change 0123 sequence to force application load local file first. Here is a example.([Whirlpool] pieces) [pieces.zip](https://github.com/jszhtian/Fragment/files/4036196/pieces.zip) Because of stupid Character Range check function, This game can only display Shift-JIS or ANSI character. If you want to display other character, you need change MBCS range check or build a Font File like console game.
> > > > 
> > > > 
> > > > Can you tell how to change MBCS range with Olldby? I want the game to read the script in utf8
> > > 
> > > 
> > > Normal MBCS check is something like [cmp al,0x9F]. But the modify version Yu-Ris has their own MBCS check because it uses plaintext scenario instead of normal ybn file. Which means you need modify the parser which is written by the 3rd party. For my side, write a new Font file is much easy compared to modify custom MBCS check.
> > 
> > 
> > Do you know how to wrap Yu-ris? I don't feel like using space for every word-wrap. ![image](https://user-images.githubusercontent.com/81801486/140083731-332afb34-e5e9-4374-b2bf-a0c220ef5c0d.png)
> 
> try use `\n`

Doesn't work \r \n /n. The only way is to space

**Comment by jszhtian** [comment]
> > > > Open Ollydbg and check the file load routing, change 0123 sequence to force application load local file first. Here is a example.([Whirlpool] pieces) [pieces.zip](https://github.com/jszhtian/Fragment/files/4036196/pieces.zip) Because of stupid Character Range check function, This game can only display Shift-JIS or ANSI character. If you want to display other character, you need change MBCS range check or build a Font File like console game.
> > > 
> > > 
> > > Can you tell how to change MBCS range with Olldby? I want the game to read the script in utf8
> > 
> > 
> > Normal MBCS check is something like [cmp al,0x9F]. But the modify version Yu-Ris has their own MBCS check because it uses plaintext scenario instead of normal ybn file. Which means you need modify the parser which is written by the 3rd party. For my side, write a new Font file is much easy compared to modify custom MBCS check.
> 
> Tks for the tip. Btw if anyone looking for repacking .ypf ver 500 try this :https://github.com/davidescrima9/YPF_Manager_Tool It can unpack/repack .ypf and print info of yu-ris version

Actually, I make a mistake here. For Yu-RIS game. It uses a char[] array to check the character is DWORD or not. It uses the high bytes to get the bool value from the array. This array can be found near the drawtext or drawchar operation. However, you only use the ASCII characters. There is no difference between Shift-JIS and ASCII in ASCII range.

**Comment by Cosetto** [comment]
> > > > > Open Ollydbg and check the file load routing, change 0123 sequence to force application load local file first. Here is a example.([Whirlpool] pieces) [pieces.zip](https://github.com/jszhtian/Fragment/files/4036196/pieces.zip) Because of stupid Character Range check function, This game can only display Shift-JIS or ANSI character. If you want to display other character, you need change MBCS range check or build a Font File like console game.
> > > > 
> > > > 
> > > > Can you tell how to change MBCS range with Olldby? I want the game to read the script in utf8
> > > 
> > > 
> > > Normal MBCS check is something like [cmp al,0x9F]. But the modify version Yu-Ris has their own MBCS check because it uses plaintext scenario instead of normal ybn file. Which means you need modify the parser which is written by the 3rd party. For my side, write a new Font file is much easy compared to modify custom MBCS check.
> > 
> > 
> > Tks for the tip. Btw if anyone looking for repacking .ypf ver 500 try this :https://github.com/davidescrima9/YPF_Manager_Tool It can unpack/repack .ypf and print info of yu-ris version
> 
> Actually, I make a mistake here. For Yu-RIS game. It uses a char[] array to check the character is DWORD or not. It uses the high bytes to get the bool value from the array. This array can be found near the drawtext or drawchar operation. However, you only use the ASCII characters. There is no difference between Shift-JIS and ASCII in ASCII range.

Do you know how to line break for Yu-ris or word wrap?

**Comment by jszhtian** [comment]
> > > > > > Open Ollydbg and check the file load routing, change 0123 sequence to force application load local file first. Here is a example.([Whirlpool] pieces) [pieces.zip](https://github.com/jszhtian/Fragment/files/4036196/pieces.zip) Because of stupid Character Range check function, This game can only display Shift-JIS or ANSI character. If you want to display other character, you need change MBCS range check or build a Font File like console game.
> > > > > 
> > > > > 
> > > > > Can you tell how to change MBCS range with Olldby? I want the game to read the script in utf8
> > > > 
> > > > 
> > > > Normal MBCS check is something like [cmp al,0x9F]. But the modify version Yu-Ris has their own MBCS check because it uses plaintext scenario instead of normal ybn file. Which means you need modify the parser which is written by the 3rd party. For my side, write a new Font file is much easy compared to modify custom MBCS check.
> > > 
> > > 
> > > Tks for the tip. Btw if anyone looking for repacking .ypf ver 500 try this :https://github.com/davidescrima9/YPF_Manager_Tool It can unpack/repack .ypf and print info of yu-ris version
> > 
> > 
> > Actually, I make a mistake here. For Yu-RIS game. It uses a char[] array to check the character is DWORD or not. It uses the high bytes to get the bool value from the array. This array can be found near the drawtext or drawchar operation. However, you only use the ASCII characters. There is no difference between Shift-JIS and ASCII in ASCII range.
> 
> Do you know how to line break for Yu-ris or word wrap?
It looks that your game use YBN as script file,
Normally you need follow the ASCII code. In ASCII it is 0x0A. So, try directly add 0x0A in the ybn script. If it works. Write a replace function in your processing application to replace "\n" as 0x0A. There is also possible that ybn not support break line, because the ybn itself is compiled by the yu-ris. The compiler has processed all break line when it does some pre-processing, in this case, it is no need to keep line break function.
Some engines also support to use \n \r \t to control the line break. but I am not sure it works for yu-ris.

**Comment by Veshurik** [comment]
I am sorry to reopen this thread so late, but I wonder how you fix the error that file "yst00034.ybn duplicated"?
It only happens when I try to pack script files back into .ypf and try to test the game. I absolutely don't understand what's wrong, and it doesn't matter if the game stores on C drive or D drive. Thanks!
![photo_2024-11-10_11-39-28](https://github.com/user-attachments/assets/71c45451-6443-4b3e-b1d9-98f27d459d60)

**Comment by CodeSpoof** [comment]
> I still don't know how to guess the key for extybn but I found this https://web.archive.org/web/20140208002246/http://tlwiki.org/images/0/02/OzmafiaScriptThing.7z. Seems like it can auto guess the key and extract the text but I'm not sure if this is the full text since the tool is made for old Yu-ris. Btw I'm trying with golden hour (ver 500) ![image](https://user-images.githubusercontent.com/91543117/140052386-6d10b96b-7b78-4abb-8324-66d52f2afdd4.png)

Do you by any chance have the sdk for version 500? Somehow the newest Version on the website is 494, but I could have sworn, that it was available at one point.

**Comment by Cosetto** [comment]
[Vntextpatch](https://github.com/arcusmaximus/VNTranslationTools) can deal with all that now. Use it to extract/insert the text (no need to find the key since it will find and decrypt/encrypt while extracting/inserting process)

**Comment by CodeSpoof** [comment]
I'm making a fully functional decompiler for YuRIS and need tge sdk for testing. My goal is to modify not only text, but also logic.

**Comment by Cosetto** [comment]
https://github.com/ZQF-ReVN/RxYuris (Has GuessXorKey)
https://github.com/crskycode/YuRis_Tool
https://github.com/2439905184/Galgame-Engine-Collect/releases/tag/v1.5.1 (Yuris SDK)
